# Site Ayarları
title: My Jekyll Site
description: Welcome to my Jekyll site

# Tema ve Renk Özelleştirmeleri
theme: jekyll-theme-modernist

# Stil Özelleştirmeleri
sass:
  style: compressed

# Özel Değişkenler
custom_colors:
  primary: "#3498db"  # Ana Renk (Mavi)
  secondary: "#e74c3c"  # İkincil Renk (Kırmızı)
  background: "#f4f4f9"  # Arka Plan Rengi
  text: "#333"  # Metin Rengi

# Düzeni Temiz Tut
permalink: /:title/
paginate: 6

# Basit Eklentiler
plugins:
  - jekyll-feed
  - jekyll-seo-tag
