# Site Temel Ayarları
title: My Jekyll Blog
description: Welcome to my blog site
theme: jekyll-theme-modernist

# Site Bağlantı Ayarları
url: "https://emredeveloper.github.io"  # Site adresi
baseurl: ""  # Repository adı boş bırakıldı

# Yayın Bağlantısı Ayarları
permalink: /:title/  # Daha sade bağlantı
