# Site Ayarları
title: My Jekyll Blog
description: Welcome to my blog site
theme: jekyll-theme-modernist

# URL ve Yayın Bağlantıları
url: "https://emredeveloper.github.io"  # Site adresi
baseurl: "/ilk-blogum"  # Repository adı
permalink: /:categories/:title/
