# Site Ayarları
title: My Jekyll Blog
description: Welcome to my blog site
theme: jekyll-theme-modernist

# URL Ayarları
url: "https://emredeveloper.github.io"  # Site adresi
baseurl: "veribilimi.github.io"  # Repository adı boş bırakıldı
