title: My Jekyll Blog
description: Welcome to my blog site
theme: jekyll-theme-modernist

# Site Ayarları
url: "https://emredeveloper.github.io"  # Site adresi
baseurl: "/ilk-blogum"  # Repository adı

# Yayın Bağlantısı Ayarları
permalink: /:categories/:title/
